# -*- mode: ruby -*-
# vi: set ft=ruby:

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

    NodeCount = 1

    (1..NodeCount).each do |i|
        config.vm.define  "judicael#(i)" do |node|
            node.vm.box = "ubuntu/bionic64"
                node.disksize.size = '20GB'
            node.vm.hostname = "judicael#{i}.example.com"
            node.vm.network "private_network", ip: "172.42.42.10#{i}"
            node.vm.provider "virtualbox" do |v|
                v.name = "judicael0#{i}"
                v.memory = 8192
                v.cpus = 2
            end
        end
    end
end